#!/usr/bin/env python3
"""
grab_retractor.py — ArUco-guided retractor handle approach
===========================================================

TRANSFORM CHAIN
---------------
ArUco solvePnP gives T_marker_cam: the 4×4 pose of the marker in camera frame.

  T_marker_cam   — marker origin in camera frame  (from solvePnP)
  T_cam_base     — camera in robot base frame      (loaded from T_cam_to_base.npy, metres)
  T_marker_base  = T_cam_base @ T_marker_cam       — marker in robot base frame
  T_offset       = pure translation [+5 cm, 0, 0] in MARKER's local X direction
                   (ArUco X points right when facing the marker; marker is on the
                    left side of the handle, so +X reaches the handle centre)
  T_target_base  = T_marker_base @ T_offset        — grab target in robot base frame
  pos_mm         = T_target_base[:3, 3] * 1000     — position sent to xArm (mm)
  hover_z        = pos_mm[2] + HOVER_CLEARANCE_MM  — hover above before descending

ArUco marker coordinate frame (solvePnP object points convention used here):
  Corner order: top-left, top-right, bottom-right, bottom-left (standard ArUco)
  +X  points RIGHT  (when facing the marker)
  +Y  points UP
  +Z  points OUT OF the marker surface toward the camera

USAGE
-----
  python surgical_test/grab/grab_retractor.py [ARM_IP]

CONTROLS
--------
  G — grab: move to hover pose (only fires when detection is STABLE)
  R — reset stability buffer and "moved" flag
  H — go to home joint angles
  Q / ESC — quit
"""

import sys
import os
import time
import math
from collections import deque

import cv2
import numpy as np

try:
    import pyrealsense2 as rs
except ImportError:
    print("ERROR: pyrealsense2 not installed. Run: pip install pyrealsense2")
    sys.exit(1)

# Add repo root to path for xarm imports
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

try:
    from xarm.wrapper import XArmAPI
except ImportError:
    print("ERROR: xarm package not found. Run from the repo root or install the package.")
    sys.exit(1)


# ===========================================================================
# ▼▼▼  CALIBRATION — REPLACE THESE VALUES  ▼▼▼
# ===========================================================================

# Robot IP address
ROBOT_IP = "192.168.1.113"   # ← replace with your xArm IP

# Path to the hand-eye calibration matrix (metres, 4×4 float64).
# Generated by surgical_test/cv/cv_calibration.py.
# If you have a different path or want to paste the matrix directly, see below.
_CALIB_PATH = os.path.join(os.path.dirname(__file__), "..", "cv", "T_cam_to_base.npy")

# --- OPTION A: load from file (recommended) ---
# T_CAM_TO_BASE = np.load(_CALIB_PATH)          # uncomment after calibration

# --- OPTION B: paste your 4×4 matrix directly (metres) ---
# T_CAM_TO_BASE = np.array([
#     [ r00,  r01,  r02,  tx ],
#     [ r10,  r11,  r12,  ty ],
#     [ r20,  r21,  r22,  tz ],
#     [  0,    0,    0,   1  ],
# ], dtype=np.float64)

# PLACEHOLDER — remove once either option above is set
T_CAM_TO_BASE = None   # ← replace with np.load(...) or a numeric matrix

# Camera intrinsics for the D435i RGB stream.
# You can read these live from the RealSense SDK (see _build_cam_matrix_from_intr)
# or paste them here if you measured them separately.
#
# Example (replace values):
#   fx = 615.0   fy = 615.0   cx = 320.0   cy = 240.0
#   k1 = 0.0   k2 = 0.0   p1 = 0.0   p2 = 0.0   k3 = 0.0
#
# Set USE_REALSENSE_INTRINSICS = True to pull them automatically from the
# RealSense SDK profile (recommended), or set to False and fill in below.
USE_REALSENSE_INTRINSICS = True   # ← set False if you want manual values

# Used only when USE_REALSENSE_INTRINSICS = False:
CAM_MATRIX_MANUAL = np.array([
    [615.0,   0.0, 320.0],   # ← replace fx, cx
    [  0.0, 615.0, 240.0],   # ← replace fy, cy
    [  0.0,   0.0,   1.0],
], dtype=np.float64)
DIST_COEFFS_MANUAL = np.zeros(5, dtype=np.float64)   # ← replace if non-zero

# ===========================================================================
# ▼▼▼  TARGET GEOMETRY  ▼▼▼
# ===========================================================================

# ArUco marker settings
MARKER_ID     = 0           # ← ID of the retractor ArUco marker
MARKER_SIZE_M = 0.08        # physical side length in metres (8 cm)
ARUCO_DICT_ID = cv2.aruco.DICT_4X4_50

# Offset from marker origin to grab target, expressed in MARKER frame (metres).
# +X = right  when facing the marker
# +Y = up     when facing the marker
# +Z = toward camera (out of marker surface)
#
# The marker is on the LEFT side of the handle → shift +5 cm in marker +X
# to reach the handle centre.
OFFSET_IN_MARKER_M = np.array([0.05, 0.0, 0.0])   # ← adjust if needed

# ===========================================================================
# ▼▼▼  ROBOT ORIENTATION AT TARGET  ▼▼▼
# ===========================================================================

# End-effector orientation at the hover / grab pose (degrees, xArm ZYX convention).
# -90 pitch = pointing straight down. Adjust roll/yaw for your gripper geometry.
TARGET_ROLL_DEG  =   0.0   # ← replace
TARGET_PITCH_DEG = -90.0   # straight down (good starting point)
TARGET_YAW_DEG   =   0.0   # ← replace

# ===========================================================================
# ▼▼▼  SAFETY PARAMETERS  ▼▼▼
# ===========================================================================

# Clearance above the computed target for the hover approach (mm).
HOVER_CLEARANCE_MM = 50.0

# Detection stability: require this many consecutive frames within threshold.
STABLE_FRAMES      = 5
STABILITY_THRESH_M = 0.003   # 3 mm max std of tvec across stable window

# Motion speed (mm/s)
SPEED_MM_S = 50

# Workspace bounds in xArm base frame (mm). Targets outside this box are
# rejected. Tighten these to match your physical setup.
WORKSPACE_BOUNDS = {
    "x": (-600.0,  600.0),
    "y": (-600.0,  600.0),
    "z": (  50.0,  700.0),
}

# Home joint angles (degrees)
HOME_JOINTS = [0, -45, 0, 45, 0, 90, 0]

# ===========================================================================
# Camera stream
# ===========================================================================

STREAM_WIDTH  = 640
STREAM_HEIGHT = 480
STREAM_FPS    = 30


# ===========================================================================
# Stability tracker
# ===========================================================================

class StabilityBuffer:
    """
    Collects translation vectors over the last N frames and reports whether
    the marker pose has been stable (low variance) for that window.
    """

    def __init__(self, n: int, thresh_m: float):
        self.n      = n
        self.thresh = thresh_m
        self.tvecs  = deque(maxlen=n)
        self.rvecs  = deque(maxlen=n)

    def reset(self):
        self.tvecs.clear()
        self.rvecs.clear()

    def update(self, rvec: np.ndarray, tvec: np.ndarray):
        self.tvecs.append(tvec.flatten().copy())
        self.rvecs.append(rvec.flatten().copy())

    def is_stable(self) -> bool:
        if len(self.tvecs) < self.n:
            return False
        arr = np.array(self.tvecs)
        return float(np.max(np.std(arr, axis=0))) < self.thresh

    def mean_pose(self):
        """Return (mean_rvec, mean_tvec) averaged over the buffer."""
        return (
            np.mean(self.rvecs, axis=0),
            np.mean(self.tvecs, axis=0),
        )


# ===========================================================================
# Homogeneous transform helpers
# ===========================================================================

def rvec_tvec_to_T(rvec: np.ndarray, tvec: np.ndarray) -> np.ndarray:
    """Convert a Rodrigues rotation vector + translation vector to a 4×4 transform."""
    R, _ = cv2.Rodrigues(rvec)
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = R
    T[:3,  3] = tvec.flatten()
    return T


def make_offset_T(offset_xyz: np.ndarray) -> np.ndarray:
    """Return a 4×4 pure-translation homogeneous matrix."""
    T = np.eye(4, dtype=np.float64)
    T[:3, 3] = offset_xyz
    return T


# ===========================================================================
# Safety check
# ===========================================================================

def within_workspace(pos_mm: np.ndarray) -> bool:
    bounds = WORKSPACE_BOUNDS
    return (
        bounds["x"][0] <= pos_mm[0] <= bounds["x"][1] and
        bounds["y"][0] <= pos_mm[1] <= bounds["y"][1] and
        bounds["z"][0] <= pos_mm[2] <= bounds["z"][1]
    )


# ===========================================================================
# xArm helpers
# ===========================================================================

def connect_arm(ip: str) -> XArmAPI:
    arm = XArmAPI(ip, do_not_open=True)
    arm.connect()
    if arm.error_code != 0:
        arm.clean_error()
    arm.motion_enable(enable=True)
    arm.set_mode(0)
    arm.set_state(0)
    time.sleep(0.5)
    print(f"[xArm] Connected to {ip}")
    return arm


def go_home(arm: XArmAPI) -> None:
    print("[xArm] Moving to home …")
    arm.set_servo_angle(angle=HOME_JOINTS, speed=30, wait=True)


def move_hover(arm: XArmAPI, pos_mm: np.ndarray) -> bool:
    """
    Move to a hover pose HOVER_CLEARANCE_MM above the target position.
    Returns True on success, False if the arm reports an error.
    """
    hover_z = float(pos_mm[2]) + HOVER_CLEARANCE_MM
    x, y = float(pos_mm[0]), float(pos_mm[1])

    print(f"[xArm] Moving to hover ({x:.1f}, {y:.1f}, {hover_z:.1f}) mm …")
    code = arm.set_position(
        x=x, y=y, z=hover_z,
        roll=TARGET_ROLL_DEG,
        pitch=TARGET_PITCH_DEG,
        yaw=TARGET_YAW_DEG,
        speed=SPEED_MM_S,
        wait=True,
    )
    if code not in (0, None):
        print(f"[xArm] WARNING: set_position returned code={code}")
        return False
    print("[xArm] Hover reached.")
    return True


# ===========================================================================
# RealSense helpers
# ===========================================================================

def open_realsense():
    pipeline = rs.pipeline()
    config   = rs.config()
    config.enable_stream(rs.stream.color, STREAM_WIDTH, STREAM_HEIGHT, rs.format.bgr8, STREAM_FPS)
    profile  = pipeline.start(config)
    intr     = (
        profile.get_stream(rs.stream.color)
               .as_video_stream_profile()
               .get_intrinsics()
    )
    print(f"[RealSense] Started {STREAM_WIDTH}×{STREAM_HEIGHT} @ {STREAM_FPS} fps")
    return pipeline, intr


def get_color_frame(pipeline) -> np.ndarray | None:
    frames = pipeline.wait_for_frames()
    cf = frames.get_color_frame()
    return np.asanyarray(cf.get_data()) if cf else None


def _build_cam_matrix_from_intr(intr) -> tuple[np.ndarray, np.ndarray]:
    """Build OpenCV camera matrix and distortion coefficients from RealSense intrinsics."""
    cam_matrix = np.array([
        [intr.fx,     0.0, intr.ppx],
        [    0.0, intr.fy, intr.ppy],
        [    0.0,     0.0,      1.0],
    ], dtype=np.float64)
    dist_coeffs = np.array(intr.coeffs, dtype=np.float64)
    return cam_matrix, dist_coeffs


# ===========================================================================
# ArUco detection and pose estimation
# ===========================================================================

def build_detector():
    dictionary = cv2.aruco.getPredefinedDictionary(ARUCO_DICT_ID)
    if hasattr(cv2.aruco, "ArucoDetector"):
        params   = cv2.aruco.DetectorParameters()
        detector = cv2.aruco.ArucoDetector(dictionary, params)
        return detector, dictionary, "new"
    else:
        params = cv2.aruco.DetectorParameters_create()
        return None, dictionary, params


def detect_target_marker(frame: np.ndarray, detector_bundle, cam_matrix, dist_coeffs):
    """
    Detect MARKER_ID in frame and estimate its 6-DOF pose via solvePnP.

    Object points follow the standard ArUco layout (Z=0 plane, centred at origin):
      corner 0 → top-left    (-X, +Y)
      corner 1 → top-right   (+X, +Y)
      corner 2 → bottom-right (+X, -Y)
      corner 3 → bottom-left (-X, -Y)

    This means +X = right, +Y = up, +Z = toward camera when facing the marker.

    Returns (rvec, tvec, corner_set) or (None, None, None) if not found.
    """
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    detector, dictionary, extra = detector_bundle

    if extra == "new":
        corners, ids, _ = detector.detectMarkers(gray)
    else:
        corners, ids, _ = cv2.aruco.detectMarkers(gray, dictionary, parameters=extra)

    if ids is None:
        return None, None, None

    for corner_set, mid in zip(corners, ids.flatten()):
        if int(mid) != MARKER_ID:
            continue

        half = MARKER_SIZE_M / 2.0
        obj_pts = np.array([
            [-half,  half, 0.0],   # corner 0: top-left
            [ half,  half, 0.0],   # corner 1: top-right
            [ half, -half, 0.0],   # corner 2: bottom-right
            [-half, -half, 0.0],   # corner 3: bottom-left
        ], dtype=np.float64)

        img_pts = corner_set.reshape(4, 2).astype(np.float64)
        ok, rvec, tvec = cv2.solvePnP(obj_pts, img_pts, cam_matrix, dist_coeffs)
        if ok:
            return rvec, tvec, corner_set

    return None, None, None


# ===========================================================================
# Visualisation
# ===========================================================================

def draw_overlay(frame, rvec, tvec, corner_set, stable, cam_matrix, dist_coeffs,
                 target_mm=None):
    overlay = frame.copy()

    if rvec is not None and tvec is not None:
        # Draw the 3D coordinate axes on the marker face
        cv2.drawFrameAxes(overlay, cam_matrix, dist_coeffs, rvec, tvec,
                          MARKER_SIZE_M / 2)

        # Highlight the detected marker border
        if corner_set is not None:
            pts = corner_set.reshape(4, 2).astype(int)
            cv2.polylines(overlay, [pts], isClosed=True,
                          color=(0, 255, 0), thickness=2)
            cx = int(pts[:, 0].mean())
            cy = int(pts[:, 1].mean())
            cv2.circle(overlay, (cx, cy), 5, (0, 255, 0), -1)

        # Stability indicator
        if stable:
            status_text  = "STABLE  —  press G to hover"
            status_color = (0, 255, 0)
        else:
            filled = len([1 for _ in range(1)])   # just for layout
            status_text  = f"Acquiring stability …"
            status_color = (0, 200, 255)
    else:
        status_text  = f"Marker ID {MARKER_ID} not detected"
        status_color = (0, 0, 255)

    cv2.putText(overlay, status_text, (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, status_color, 2)
    cv2.putText(overlay, "G=hover  R=reset  H=home  Q=quit",
                (10, STREAM_HEIGHT - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), 1)

    if target_mm is not None:
        info = (f"Target (base): "
                f"x={target_mm[0]:.1f}  y={target_mm[1]:.1f}  z={target_mm[2]:.1f} mm")
        cv2.putText(overlay, info, (10, 60),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 100), 2)

    return overlay


# ===========================================================================
# Main
# ===========================================================================

def run():
    # --- Validate calibration ---
    global T_CAM_TO_BASE
    if T_CAM_TO_BASE is None:
        calib_abs = os.path.abspath(_CALIB_PATH)
        if os.path.exists(calib_abs):
            T_CAM_TO_BASE = np.load(calib_abs)
            print(f"[grab] Loaded T_cam_to_base from {calib_abs}")
        else:
            print(
                "ERROR: T_CAM_TO_BASE is not set and calibration file not found:\n"
                f"  {calib_abs}\n"
                "Either run surgical_test/cv/cv_calibration.py first, or paste\n"
                "your 4×4 matrix directly into the T_CAM_TO_BASE variable above."
            )
            sys.exit(1)

    print("[grab] T_cam_to_base =")
    print(np.array2string(T_CAM_TO_BASE, precision=4, suppress_small=True))

    # --- Connect arm ---
    ip = sys.argv[1] if len(sys.argv) > 1 else ROBOT_IP
    arm = connect_arm(ip)

    # --- Open camera ---
    pipeline, rs_intr = open_realsense()

    if USE_REALSENSE_INTRINSICS:
        cam_matrix, dist_coeffs = _build_cam_matrix_from_intr(rs_intr)
        print(f"[grab] Using RealSense intrinsics: "
              f"fx={rs_intr.fx:.2f}  fy={rs_intr.fy:.2f}  "
              f"cx={rs_intr.ppx:.2f}  cy={rs_intr.ppy:.2f}")
    else:
        cam_matrix  = CAM_MATRIX_MANUAL
        dist_coeffs = DIST_COEFFS_MANUAL
        print("[grab] Using manually specified intrinsics.")

    detector_bundle = build_detector()
    buf    = StabilityBuffer(STABLE_FRAMES, STABILITY_THRESH_M)
    moved  = False   # prevents re-triggering until reset
    last_rvec = last_tvec = last_corner = None
    last_target_mm = None

    print(
        "\n[grab] Live feed started.\n"
        f"  Target: marker ID {MARKER_ID}, offset +{OFFSET_IN_MARKER_M[0]*100:.0f} cm in marker +X\n"
        "  G=hover  R=reset  H=home  Q/ESC=quit\n"
    )

    try:
        while True:
            frame = get_color_frame(pipeline)
            if frame is None:
                continue

            rvec, tvec, corner_set = detect_target_marker(
                frame, detector_bundle, cam_matrix, dist_coeffs)

            if rvec is not None:
                buf.update(rvec, tvec)
                last_rvec, last_tvec, last_corner = rvec, tvec, corner_set
            else:
                buf.reset()

            stable = buf.is_stable()

            # Compute the live target for display (doesn't move the arm)
            if stable and last_rvec is not None:
                mean_rvec, mean_tvec = buf.mean_pose()
                T_marker_cam  = rvec_tvec_to_T(mean_rvec, mean_tvec)
                T_marker_base = T_CAM_TO_BASE @ T_marker_cam
                T_offset      = make_offset_T(OFFSET_IN_MARKER_M)
                T_target_base = T_marker_base @ T_offset
                last_target_mm = T_target_base[:3, 3] * 1000.0
            else:
                last_target_mm = None

            display = draw_overlay(
                frame, last_rvec, last_tvec, last_corner, stable,
                cam_matrix, dist_coeffs, last_target_mm)
            cv2.imshow("grab_retractor", display)

            key = cv2.waitKey(1) & 0xFF

            # ---- G: go to hover ----
            if key == ord("g"):
                if moved:
                    print("[grab] Already moved. Press R to reset before grabbing again.")
                elif not stable:
                    print("[grab] Detection not stable yet — keep the marker still.")
                else:
                    target_mm = last_target_mm
                    print(f"\n[grab] Target in base frame: "
                          f"({target_mm[0]:.1f}, {target_mm[1]:.1f}, {target_mm[2]:.1f}) mm")

                    if not within_workspace(target_mm):
                        print(
                            f"[grab] ABORT: target {target_mm} is outside workspace bounds "
                            f"{WORKSPACE_BOUNDS}. Check calibration and marker placement."
                        )
                    else:
                        success = move_hover(arm, target_mm)
                        if success:
                            moved = True

            # ---- R: reset ----
            elif key == ord("r"):
                print("[grab] Reset.")
                buf.reset()
                moved = False
                last_target_mm = None

            # ---- H: home ----
            elif key == ord("h"):
                go_home(arm)
                moved = False

            # ---- Q / ESC: quit ----
            elif key in (ord("q"), 27):
                print("[grab] Quit.")
                break

    finally:
        pipeline.stop()
        arm.disconnect()
        cv2.destroyAllWindows()
        print("[grab] Done.")


if __name__ == "__main__":
    run()
